### ISSUE TITLE
Add implicit cast from Mock<T> to T

### ISSUE THREAD

**Issue by nminaya** [devlooped/moq#1097]
Have you consider adding an implicit cast to Mock class in order to be able to cast implicitly ```Mock<T>``` to ```T```?

This implicit cast should return the mock.Object instance.

**Comment by stakx** [comment]
This has been tried in the past, but it turns out it doesn't work reliably.

https://github.com/moq/moq4/blob/9638d0d6df2e9b89eb3090e19a1c566786b18dd6/Source/Mock.Generic.cs#L493-L504

(That link is broken, but the reason for this not working is found in the [C# specification which disallows such user-defined conversions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#permitted-user-defined-conversions).)

Let me demonstrate the issue. Let's just go ahead and add the implicit conversion operator to `Mock<T>`:

```diff
+	public static implicit operator T(Mock<T> mock)
+	{
+		return mock.Object;
+	}
```

Now let's see if it works:

```csharp
public interface IFrobble { }

static void Fiddle(IFrobble frobble) => Console.WriteLine(frobble);

var frobbleMock = new Mock<IFrobble>();
Fiddle(frobbleMock);  // CS1501: Argument 1: cannot convert from 'Moq.Mock<IFrobble>' to 'IFrobble'
```

OK, that didn't work. Maybe this?:

```csharp
var frobbleMock = new Mock<IFrobble>();
IFrobble frobble = frobbleMock;  // CS0266: Cannot implicitly convert type 'Moq.Mock<IFrobble>' to 'IFrobble'.
                                 // An explicit conversion exists (are you missing a cast?)
```

Hmm, let's follow that suggestion:

```csharp
var frobbleMock = new Mock<IFrobble>();
var frobble = (IFrobble)frobbleMock;  // System.InvalidCastException: Unable to cast object of type
                                      // 'Moq.Mock<IFrobble>' to type 'IFrobble'.
```

Now make this change:

```diff
-public interface IFrobble { }
+public class IFrobble { }
```

and suddenly all of the above test cases work just fine.

Having this "feature" work only some of the time is no good and confusing, so let's not go there.
