### ISSUE TITLE
How to mock the this.context.Database.BeginTransaction() in Asp.net Core?

### ISSUE THREAD

**Issue by Tarakeswarab** [devlooped/moq#1143]
How to mock the this.context.Database.BeginTransaction() in Asp.net Core?

Unable to mock the Begin Transaction in EF.

**Comment by stakx** [comment]
@Tarakeswarab this issue tracker's focus is on developing Moq 4. We occasionally answer usage questions if it appears as if a problem could be caused by e.g. a bug or limitation in Moq. However, you're better off asking pure usage questions on sites such as Stack Overflow. You'll find a much bigger audience there.
