### ISSUE TITLE
Why is there no It.IsNull<T>?

### ISSUE THREAD

**Issue by jez9999** [devlooped/moq#1151]
Moq has an `It.IsNotNull<T>` option when doing a `.Setup()` for a mocked object, so why is there no `It.IsNull<T>`?  Seems like a logical addition, and it would achieve the same as the rather more verbose `It.Is<T>(o => o == null)`.

**Comment by stakx** [comment]
@jez9999, simple answer: because it isn't needed. Instead of `It.IsNull<T>()`, simply use `null`. Constant values don't require any matcher. After all, you'd also use `42` instead of `It.Is<int>(x => x == 42)`, right?

**Comment by jez9999** [comment]
> @jez9999, simple answer: because it isn't needed. Instead of `It.IsNull<T>()`, simply use `null`. Constant values don't require any matcher. After all, you'd also use `42` instead of `It.Is<int>(x => x == 42)`, right?

Don't know whether I'm missing something, but I don't see an overload of `Is` that just takes `T`.  Closest is `TValue, IEqualityComparer<T>`.

**Comment by jez9999** [comment]
Just realized you meant to avoid using `It.Is` at all and replace the whole thing with `null`.  Yeah, that works.  Although, if you had 2 method overloads with 2 different reference types, how would Moq know which one was being referenced?

**Comment by stakx** [comment]
@jez9999 `null` doesn't carry any type information, it is implicitly convertible to any reference type or nullable value type. That being said, the C# compiler will pick a matching method overload. If overload resolution is ambiguous you may have to help out the compiler by casting it to the correct static type, `(ParameterType)null` &ndash; or `default(ParameterType)` if you prefer.

**Comment by stakx** [comment]
Regarding your other question, for the sake of completeness (even though you won't need it here), there most definitely _is_ an overload `It.Is<TValue>(predicate)`, it is defined [here](https://github.com/moq/moq4/blob/b7b07279c45c29a201399a7fa93764892422e687/src/Moq/It.cs#L139).

**Comment by jez9999** [comment]
> Regarding your other question, for the sake of completeness (even though you won't need it here), there most definitely _is_ an overload `It.Is<TValue>(predicate)`, it is defined [here](https://github.com/moq/moq4/blob/b7b07279c45c29a201399a7fa93764892422e687/src/Moq/It.cs#L139).

That takes `Expression<Func<TValue, bool>> match`, so requires saying `x => x == null`.

**Comment by stakx** [comment]
I see, you were referring to an overload `It.Is<T>(x)` where `x` is a `T`. Yes, that indeed doesn't exist, for the same reason that we don't need `It.IsNull`: you just write `x` instead of `It.Is<T>(x)` &ndash; no matcher required for fixed values.

**Comment by MrMartinNielsen** [comment]
I ended up here because i was (also) missing a "null match"-thingy.
To improve discoverability, dare i suggest adding a remark to the It.IsAny<T> stating something along the lines of: "does not match null".
The image is supposed to illustrate the experience i have in mind :) 
![image](https://user-images.githubusercontent.com/55786981/225566003-127ed2f6-ccbc-48a7-961d-0ff436d9629c.png)

**Comment by stakx** [comment]
Such a doc comment would be factually incorrect, because `It.IsAny<T>()` _does_ match `null` references when `T` is a reference type or nullable value type. (There may be a few rare, weird edge cases where that doesn't apply, but never mind those for the moment.)

It's really quite simple: if you want to match a specific value (be it `null`, or `42`, or whatever), use that exact value. If you don't care about the parameter and want to match anything, use `It.IsAny`. For pretty much everything else `It.Is` would be the likely choice. Everyting else is for rarer, more specialized use cases.

**Comment by MrMartinNielsen** [comment]
Ah, okay in that case it is _supposed to work_ as i would expect - i guess i am just running into the _rare weird edge case_ ¯\_(ツ)_/¯
I can live with the workaround of just matching on _null_ though so all good.

Thank you for reply :)
