### ISSUE TITLE
Returning list from mocked generic method fails

### ISSUE THREAD

**Issue by PerProjBackup** [devlooped/moq#1160]
Visual Studio 2019 Enterprise 16.9.4; Moq 4.16.1; xunit 2.4.1

Also posted to SO:
https://stackoverflow.com/questions/67475719/returning-list-from-mocked-generic-method-fails/67483514#67483514

I'm trying to unit test my AlbumData.GetAlbumsAsync() method. I mock the SqlDataAccess layer which is making a call to the DB using Dapper in a `generic` method.

This is my setup. The mock is not working. In the AlbumData.GetAlbumsAsync() method the call to the mocked object (_sql.LoadDataAsync) returns null and output is set to null.

Can anyone tell me what I'm dong wrong?

SqlDataAccess.cs

```
public async Task<List<T>> LoadDataAsync<T, U>(string storedProcedure, U parameters, string connectionStringName)
{
    string connectionString = GetConnectionString(connectionStringName);

    using (IDbConnection connection = new SqlConnection(connectionString))
    {
      IEnumerable<T> result = await connection.QueryAsync<T>(storedProcedure, parameters,
                        commandType: CommandType.StoredProcedure);
      List<T> rows = result.ToList();
      return rows;
    }
}
```

AlbumData.cs

```
public class AlbumData : IAlbumData
{
    private readonly ISqlDataAccess _sql;
    
    public AlbumData(ISqlDataAccess sql)
    {
      _sql = sql;
    }

    public async Task<List<AlbumModel>> GetAlbumsAsync()
    {
      var output = await _sql.LoadDataAsync<AlbumModel, dynamic>
        ("dbo.spAlbum_GetAll", new { }, "AlbumConnection");

      return output;
    }
    ...
}
```
    

AlbumDataText.cs

```
public class AlbumDataTest
{
    private readonly List<AlbumModel> _albums = new()
    {
      new AlbumModel { Title = "Album1", AlbumId = 1 },
      new AlbumModel { Title = "Album2", AlbumId = 2 },
      new AlbumModel { Title = "Album3", AlbumId = 3 }
    };

    [Fact]
    public async Task getAlbums_returns_multiple_records_test()
    {
      Mock<ISqlDataAccess> sqlDataAccessMock = new();
      sqlDataAccessMock.Setup(d => d.LoadDataAsync<AlbumModel, dynamic>
        ("", new { }, "")).Returns(Task.FromResult(_albums));
        // This alternate syntax also returns null
        // ("", new { }, "").Result).Returns(_albums);
      AlbumData albumData = new AlbumData(sqlDataAccessMock.Object);

      List<AlbumModel> actual = await albumData.GetAlbumsAsync();

      Assert.True(actual.Count == 3);
    }
    ...
}
```

**Comment by JoeMumm** [comment]
@stakx this is not a pure useage issue it is a bug, please re-open.  It has been traced down to the use of `dynamic` as a generic.

      Mock<ISqlDataAccess> sqlDataAccessMock = new();
      sqlDataAccessMock.Setup(d => d.LoadDataAsync<AlbumModel, dynamic>
        (It.IsAny<string>(), new { }, It.IsAny<string>())).ReturnsAsync(_albums);

The mock is being passed into the `AlbumData` class, normally the Test class is in a separate project and under that scenario the mock fails and returns a null. If I move the `AlbumData` class into the same project as the test class the mock works and returns a list of 3 objects.  I've created a GitHub repository, [https://github.com/PerProjBackup/Failing-Mock](url), which contains a Failing and Passing folder with the two different scenarios.

Since the mock works under certain scenarios it does not appear to be a useage issue.  Real world the test class is in a separate project from the code being tested.  Why under this standard scenario does the mock fail when using the `dynamic` type as a generic?

**Comment by stakx** [comment]
@JoeMumm: This is not a bug.

This actually has nothing to do with `dynamic`. I may be simplifying a little, but `dynamic` is essentially the same as `object` once your code has been compiled. If you replace `dynamic` with `object`, you'll still see the problem.

The problem is instead caused by the usage of anonymous types, i.e. `new { }`:

Roslyn (the standard C# compiler) creates an anonymous type, say `<>f__AnonymousType0`, that it can then new up. Roslyn reuses emitted anonymous types to some extent; say if you have a LINQ query with two expressions `new { }` having the same "shape" (basically, having identical member names & types), only one anonymous type gets emitted. The precise way how this reuse works is a compiler implementation detail, and not something specified in the C# language standard (IIRC). For the issue at hand, it's important to note that anonymous type reuse does not happen across assemblies (projects)!

There are two places where this `new { }` expression occurs:

* in the test method (where a call expectation is set up), and
* in `AlbumData` (where the actual call is made).

If those two occurrences are in the same project, then everything happens to work fine. This is only thanks to the reuse of one and the same anonymous type, as we'll see in a second. (Note that this successful scenario actually relies on a compiler implementation detail in order to be successful!)

If the two occurrences of `new { }` are in different projects, then no anonymous type reuse occurs&mdash;each of the two projects gets its own anonymous type called `<>f__AnonymousType0`. They might be equivalent, but they are distinct types. So now the setup and the call site refer to different types for `new { }`, and therefore the call doesn't match the setup, and therefore the setup never triggers, thus the `NullReferenceException`, and thus the test failure.

If you replaced `new { }` in the setup with `It.IsAny<object>()`, the problem goes away. (Note that you cannot use `It.IsAny<dynamic>()` because the compiler forbids `dynamic` inside LINQ expression trees. But like I said initially, you should be able to replace `dynamic` with `object` in your mock code.)

P.S.: When working with anonymous types, keep in mind the original scenario for which they were designed: intermediate results in LINQ queries. You cannot use anonymous types as a method's return type because there's no way to refer to them, and in that original scenario, there shouldn't be any need to: instances of an anonymous type are essentially locals of the method containing the LINQ query. _That_ is how anonymous types work best; as soon as they start crossing method borders, you should treat them simply as opaque `object`s, otherwise you quickly find yourself in strange situations that can only be explained by looking under the surface.
