### ISSUE TITLE
InvalidCastException when setup mixed enumerables

### ISSUE THREAD

**Issue by haukelue** [devlooped/moq#1161]
Hi,
we tried to update our Moq-Nuget-package from 4.12.0 to a newer one. But due to a change in the Setup-Method we are stuck in the upgrade and can't use the newer version. I tried to simplify our testbase with the following code:

```C#
using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.VisualStudio.TestTools.UnitTesting;

using Moq;

namespace Internet.Web.Test.Common.Tests
{
	[TestClass]
	public class MoqSetupTests
	{
		[TestMethod]
		public void SetupMixedChildren()
		{
			var basemock = new Mock<IBase>();

			var alist = new List<IA>() { new A() };
			basemock.Setup(b => b.Children<IA>()).Returns(alist);
			basemock.Setup(b => b.Children<IBase>()).Returns(alist);

			var blist = new List<IB>() { new B() };
			basemock.Setup(b => b.Children<IB>()).Returns(blist);
			basemock.Setup(b => b.Children<IBase>()).Returns(blist);

			var baseo = basemock.Object;
			Assert.AreEqual(1, baseo.Children<IA>().Count());
			Assert.AreEqual(1, baseo.Children<IB>().Count());

			// would be nice if this could be 2
			Assert.AreEqual(1, baseo.Children<IBase>().Count());
		}
	}

	public interface IBase
	{
		IEnumerable<T> Children<T>() where T : IBase;
	}

	public class Base : IBase
	{
		public IEnumerable<T> Children<T>() where T: IBase
		{
			yield break;
		}
	}

	public interface IA : IBase
	{
		IBase Parent { get; set; }
	}

	public class A : Base, IA
	{
		public IBase Parent { get; set; }
	}

	public interface IB : IBase
	{
		IBase Parent { get; set; }
	}

	public class B : Base, IB
	{
		public IBase Parent { get; set; }
	}
}
```

We tried to get rid of the Setup of IBase but it causes different tests to fail. Could you say how to solve the problem or how I can get rid of the error?

Greetings Hauke

**Comment by stakx** [comment]
I've seen lots of similar reports here recently. Problem is that you are ordering your setups incorrectly.

```csharp
basemock.Setup(b => b.Children<IA>()).Returns(alist);
basemock.Setup(b => b.Children<IBase>()).Returns(alist);
basemock.Setup(b => b.Children<IB>()).Returns(blist);

**Comment by stakx** [comment]
Hi @haukelue. Sorry for the delayed response... I've been rather busy at work.

I've seen lots of similar reports here recently. Problem is that you are ordering your setups incorrectly. Moq prioritises newer setups over older ones. When two setups could apply to a call, the newer one is chosen.

Take your four setups:

```csharp
basemock.Setup(b => b.Children<IA>()).Returns(alist);
basemock.Setup(b => b.Children<IBase>()).Returns(alist);
// ...
basemock.Setup(b => b.Children<IB>()).Returns(blist);
basemock.Setup(b => b.Children<IBase>()).Returns(blist);
```

Here, the very last setup effectively "shadows" all other ones because `IA` and `IB` both derive from `IBase`. That is, for instance, a call to `base.Children<IB>` matches the latter setup for `b.Children<IBase>()` because `IB` is-a `IBase`. Same reasoning goes for calls to `base.Children<IA>`. Regarding calls to `base.Children<IBase>`, there are two setups to choose; the newer one "wins".

The correct sequence of setups should be more like this:

```csharp
basemock.Setup(b => b.Children<IBase>()).Returns(blist); // or alist, whatever you prefer
basemock.Setup(b => b.Children<IA>()).Returns(alist);
basemock.Setup(b => b.Children<IB>()).Returns(blist);
```

That is, you should order your setups from least specific to most specific. Then you should start seeing your tests pass.

(And before you ask: Yes, there has been a change from previous versions causing the break you observed. Moq used to match generic arguments precisely, whereas now it takes polymorphism / subtype relationships into account. And no, it's unlikely that we'll go back to the old behaviour, because the new behaviour is more consistent overall, and also more in line with the usual .NET polymorphism rules.)

To fully answer your post, why the `InvalidCastException`? Because of this:

```csharp
basemock.Setup(b => b.Children<IBase>()).Returns(blist);
// ...
Assert.AreEqual(1, baseo.Children<IA>().Count());
```

The call to `base.Children<IA>` matches the setup `b.Children<IBase>` because `IA` is-a `IBase`, so a `List<IB>` gets returned as a result. However, the caller expects to get back an `IEnumerable<IA>`, which the `List<IB>` obviously doesn't implement. Once you reorder your setups, the newest setup matching the call will be the one for `b.Children<IA>` and there will no longer be a type mismatch.

Hope this helps! 😃
