### ISSUE TITLE
Feature - stubbing indexers

### ISSUE THREAD

**Issue by tonyhallett** [devlooped/moq#1178]
Like SetupProperty

**Comment by stakx** [comment]
I think this capability &ndash; that is, a `SetupIndexer` method for stubbing indexers similar to what `SetupProperty` does for properties &ndash; is missing in Moq with good reason:

Consider auto-implemented properties in C#:

```csharp
object Property { get; set; } = "initial value";
//              ^^^^^^^^^^^^^
```

C# will automatically generate an anonymous backing field for that property. `SetupProperty` corresponds to that syntax and essentially does the same thing:

```csharp
mock.SetupProperty(m => m.Property, "initial value");
```

When it comes to indexers, however, C# does not support the auto-implemented variety:

```csharp
object this[int index, ...] { get; set; }
//                          ^^^^^^^^^^^^^
```

> ```
> error CS0501: 'C.this[int].get' must declare a body because it is not marked abstract, extern, or partial
> error CS0501: 'C.this[int].set' must declare a body because it is not marked abstract, extern, or partial
> ```

(What would that do, anyway? Create a backing `Dictionary<,>`? Or something altogether different?)

One of the principles behind Moq is that it lets you automate what you would otherwise have to spell out manually. In the same way that `SetupProperty` mimicks auto-implemented properties, `SetupIndexer` would likely have to mimick auto-implemented indexers, and since those don't actually exist in C#, I think Moq shouldn't have that capability either.

If we were to introduce `SetupIndexer` anyway, Moq would let you do something with indexers that you normally couldn't have done anyway, suggesting that `SetupIndexer` would serve only a relatively rare use case... and it probably wouldn't pay off to have to maintain a new feature for that.

In the few occasions where you would actually need something like a dictionary-like indexer, it's already not too hard to achieve that using the existing methods:

```csharp
var mock = new Mock<IFoo>();

var dict = new Dictionary<int, object>();
mock.Setup(m => m[It.IsAny<int>()]).Returns((int index) => dict[index]);
mock.SetupSet(m => m[It.IsAny<int>()] = It.IsAny<object>()).Callback((int index, object value) => dict[index] = value);

public interface IFoo
{
    object this[int index] { get; set; }
}
```

For the reasons laid out above, my personal vote goes against `SetupIndexer`, I'm not going to review your PR at this time. I'll leave this issue open for a while in case anyone else wants to offer a different perspective.

**Comment by tonyhallett** [comment]
> In the few occasions where you would actually need something like a dictionary-like indexer, it's already not too hard to achieve that using the existing methods:

Agreed but this pull request does it for n keys.

Regardless no problem.
