### ISSUE TITLE
Verify fails when multiple invocations with the same object modified between the calls

### ISSUE THREAD

**Issue by PiotrSzymczyk** [devlooped/moq#1183]
When sut performs multiple calls to a mocked service with the same object (updated between the calls) the last invocation overrides all the previous ones:
```
        public void CallServiceWithModifiedObject()
        {
            var tst = new TstObj();
            
            tst.Prop = "a";
            _service.CreateOrUpdate(tst);
            
            // update object & call service again - e.g. update object state in DB
            tst.Prop = "b";
            _service.CreateOrUpdate(tst);
        }
```
Unable to verify both calls to a service with
```
            _serviceMock.Verify(s => s.CreateOrUpdate(It.Is<TstObj>(t => t.Prop.Equals("a"))), Times.Exactly(1));
            _serviceMock.Verify(s => s.CreateOrUpdate(It.Is<TstObj>(t => t.Prop.Equals("b"))), Times.Exactly(1));
```
### Steps to Reproduce
Issue reproduced [here](https://github.com/moq/moq4/files/6750475/Test.zip) (including unit tests)

### Expected Behavior
Both invocations can be verified by parameters

### Actual Behavior
Last invocation overwrites all prevoius calls

**Comment by stakx** [comment]
We get issues such as this one from time to time.

You said it yourself in this issue's title: it's the _same_ object.

 When Moq records an invocation (for later verification), it records precisely the objects/values passed to the invoked method; so for value typed parameters it records a (copy of the) value, and for reference typed parameters it records an object reference.

In other words, Moq observes the usual .NET equality semantics.

Moq does _not_ deep-clone whole object graphs in order to create a snapshot of that object's state at a specific moment in time.
