### ISSUE TITLE
Mocking Static Abstract Interface Methods?

### ISSUE THREAD

**Issue by the-avid-engineer** [devlooped/moq#1238]
There's a new feature currently in preview which allows you to add `static abstract` methods to an interface:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/static-abstract-interface-methods

Is there a way to add a mock behavior for such a method, using moq?

I realize there may not be a "pretty" way to do it yet, but I would like to know if there is _any_ way to do it? I'm used to the `Setup`, `SetupGet`, etc. methods, but it doesn't appear there is one for static abstract methods yet.

**Comment by stakx** [comment]
> I realize there may not be a "pretty" way to do it yet, but I would like to know if there is any way to do it?

I don't know for sure, but I suspect not. DynamicProxy still sees interfaces the way they were pre-.NET 5, and doesn't yet support all their new capabilities. Because Moq is based on DynamicProxy, it shares those same limitations... at least for now. Support for non-public, non-abstract, non-instance interface members would have to be added in DynamicProxy. Unfortunately, development (or, more precisely, the release cycle) over there has pretty much come to a halt. So I am not very optimistic that we'll be able to support your scenario anytime soon.

**Comment by crash-dive** [comment]
Just thought I would add that Moq will just error at runtime if you have strict behaviour on and the type you are mocking has a static abstract property on it even if you do not touch that property with Moq.

However if you do not need to mock that property and just want to ignore it you can implement the interface in an abstract class, implement the static properties in the abstract class and then it works like any other abstract class. Not a work around if you need to Moq the static properties, but helps at least ignore them and still use Moq so could help someone.

**Comment by the-avid-engineer** [comment]
It looks like the only viable solution, as of .NET 7, would require sacrificing strong typing.

Per compiler error `CS8920`, interfaces that define static abstract methods cannot be used as generic type arguments unless they _implement_ the static abstract methods.

So any kind of solution where you mock this kind of interface method would have to use `typeof(IMyInterface)` in some way, because `new Mock<IMyInterface>()` will throw compiler error `CS8920`.

You could get around that by extending the interface with a default implementation that throws.. but there's no Expression syntax for static type method calls.. so you'd need `nameof(IMyInterface.StaticAbstractMethod)`

Sad :(
