### ISSUE TITLE
Retaining old Setups breaks memory leak tests

### ISSUE THREAD

**Issue by aaronburro** [devlooped/moq#1239]
I'm upgrading from 4.2.1502.911 (read: very old) to get some newer whizzbang features (mostly better ref and out parameter support) and am having some issues. I see that the MoqExtensions.ResetCalls() method has been marked as obsolete, and I migrated everything to the Mock<T>.Invocations.Clear() as suggested.

However, upon running my tests, almost everything passes, and the common denominator on the failing tests seems to be that they are tests for memory leaks. When I fire up the memory profiler, I see that Moq is retaining more information than it used to, and there's no satisfactory way to clear it. The biggest culprit so far seems to be old Setup objects.

A common failure pattern that I see is if I need to use SetupGet to return the object I am testing (it's a tree-based model, so occasionally this might be necessary for some less-than-optimal scenarios, or extension method purposes). I was replacing the SetupGet() call on the property to return NULL before checking for a leak, and that was working fine until the upgrade, because the old SetupGet() is retained, which roots the object I'm testing. I've also seen some interceptors that are still hanging around, but haven't dug too deeply into them yet.

An alternative is to use Mock<T>.Reset(), but this will lead to false negatives, because it clears ALL Setups and event handlers. We all know that event handlers are the most common source of memory leaks, so clearing them makes the tests basically useless. What I really need is to be able to clear all of the internal record-keeping state of the mocks that is used by verification (similar to the old ResetCalls()) and retain just the current mock state, but it's all hidden as internal methods, fields, and classes. Is there some workaround for this that's not *too* ugly? If not, what's the last version before this record keeping stuff was added so that I can at least move up a little bit while still keeping these memory leak tests available?

An example of the common Setup scenario I face is this:

```
public interface IMain
{
    IFoo Foo { get; }
}

public class ConcreteFoo : IFoo
{
    private readonly IMain _main;
    public ConcreteFoo(IMain main) { _main = main; }
}

public class ConcreteFooTests
{
    public void TestMemoryLeak()
    {
        var main = new Mock<IMain>();
        TestUtility.TestMemoryLeak(() =>    // special method that checks for memory leaks on the object that is returned
        {
            var result = new ConcreteFoo(main.Object);
            main.SetupGet(m => m.Foo).Returns(result);
            // do some stuff
           return result;
        },
        () =>    // this action gets called before the final check if the result from above is still rooted
        {
            main.SetupGet(m => m.Foo).Returns(default(IFoo)));
            main.Invocations.Clear();    // used to be main.ResetCalls()
        }
    }
}
```

**Comment by stakx** [comment]
Why did you ever expect `mock.ResetCalls()` or `mock.Invocations.Clear()` to have any effect on _setups_? Seems like you previously relied on some implementation detail, which would make your tests unnecessarily harder to understand.

The easiest way to solve this might be for your setup to compute the return value lazily, e.g. by evaluating some variable. That way, you won't need to shadow the previous setup with a new one; you simply change the variable:

```csharp
object foo = ...;
mock.Setup(m => m.Foo).Returns(() => foo);  // lambda instead of value
...
foo = null;  // instead of another setup
```

That would seem a lot more direct for what you need your mock to do.

As to the internal changes: when you set up the same property or method a second time, the first setup is now kept around (as you noticed); it is now simply being _shadowed_ (instead of being truly _overridden_) by the latter setup. This makes a setup operation more of constant-time operation instead of a linear-time one, as Moq no longer needs to look at every previously created setup for override candidates when configuring a new setup... which is beneficial for Moq performance in the most common use case where you create setups only at the beginning, then exercise your mock (without reprogramming it again), or where you have a mock with _lots_ of setups.

To find the latest version with that new behavior, you'd need to look at the `SetupCollection.Add` method source code. The new behavior has been around a fair while, so if all you need is better `ref`/`out` support, version 4.8 might be sufficient for you.

**Comment by aaronburro** [comment]
I never expected either of those to rely on setups. Those were just what I had to call to have Moq stop rooting my objects based on what methods were called on the mocks, which makes perfect sense. Tracking previous setups is a new feature from where we currently are, so, what I'm seeing is obviously expected behaviour, just undesirable. As to your suggestion, I had already decided to do just that. It's a significant effort at retrofitting, and hopefully it will work in all scenarios that I need. But it would be nice to just be able to change the mock instead of making a dummy class variable to clear the result.

I've done quite a bit of testing with different versions and am able to pinpoint where a few of our failure scenarios start happening. Should I open a new issue for those, as they seem to be bugs, unlike the Setups issue, or would you like me to elaborate here?

**Comment by stakx** [comment]
> Those were just what I had to call to have Moq stop rooting my objects based on what methods were called on the mocks

That doesn't sound right. If you have a setup like `mock.Setup(m).Returns(x)`, that `mock` will have a reference to `x`, and `mock.ResetCalls()` won't change that; trying to replace the setup via another `mock.Setup(m).Returns(null)` on the other hand _might_ conceivably have that effect.

> Tracking previous setups is a new feature from where we currently are [.]

Moq has never made a promise that the former setup for `m` will be completely removed; the only promise is that a call to `m` will return `null` after the latter setup. How that behavior is implemented is really an internal detail.

> it would be nice to just be able to change the mock instead of making a dummy class variable

You _can_ change the mock (`mock.Reset()`), or you can simply set up a completely new one. You also don't need to reference a class field in your setup; it can be a local variable, too. Those are your calls.

I'm going to close this issue as there's nothing to be done here on Moq's side.
