### ISSUE TITLE
Setup property doesn't work as expected

### ISSUE THREAD

**Issue by Naxemar** [devlooped/moq#1248]
Hi everyone, from time to time we are performing a regular nuget update, and currently part of our previously working tests are not working any more.

IDE: VS 2022
Test Runner: vstest
Test framework: mstest
.NET Version: 4.8

Steps to reproduce:
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;

namespace MoqIssueTestProject
{
    public interface ITest1Interface
    {
        bool IsDone { get; set; }
    }

    public interface ITest2Interface : ITest1Interface
    {
    }

    public abstract class AbstractClass
    {
        public virtual bool IsDone { get; set; }
    }

    public class InheritedClass : AbstractClass, ITest1Interface
    {
    }

    public class ClassToTest
    {
        private readonly ITest1Interface instance;

        public ClassToTest(ITest1Interface instance)
        {
            this.instance = instance;
        }

        public void DoSomething()
        {
            instance.IsDone = true;
        }
    }

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            // Arrange
            var mockDependency = new Mock<InheritedClass>();
            var mockDependency2 = mockDependency.As<ITest2Interface>().SetupProperty(x => x.IsDone, false);
            var tc = new ClassToTest(mockDependency2.Object);

            // Act
            tc.DoSomething();

            // Verify
            mockDependency.VerifySet(x => x.IsDone = true, Times.Once()); // Fine
            mockDependency2.VerifySet(x => x.IsDone = true, Times.Once()); // Fine
            Assert.IsTrue(mockDependency2.Object.IsDone); // This fails
            Assert.IsTrue(mockDependency.Object.IsDone); // This fails
        }
    }
}
```

Last version where it was working as expected: 4.16.1

**Comment by stakx** [comment]
@Naxemar, thanks for reporting. I'll look into it soon.

**Comment by stakx** [comment]
This is a bug caused by [this bit of code inside `StubbedPropertySetup`](https://github.com/moq/moq4/blob/a56901655b5149c1dda38a1d843c0c6b51f9d950/src/Moq/StubbedPropertySetup.cs#L104), which compares methods in a way-too-simplistic fashion.

https://github.com/moq/moq4/blob/a56901655b5149c1dda38a1d843c0c6b51f9d950/src/Moq/StubbedPropertySetup.cs#L101-L105

This code decides whether or not the stubbed property setup will trigger for the call to `mockDependency2.Object.IsDone = true`. It doesn't correctly identify that the actual invocation's method (`InheritedClass.set_IsDone`) matches the one referred to in the setup (`ITest1Interface.set_IsDone`); but it should, because the former is the implementation of the latter.

**Comment by stakx** [comment]
Note to self: We might get away with simply comparing property names (as already happens in `StubbedPropertiesSetup`).  This just _might_ work since `SetupProperty` doesn't support indexers, so the property signature becomes irrelevant. The part I'm unsure about pertains to explicitly implemented properties: if a property is explicitly implemented due to redeclaration in a derived type, then its name isn't strictly unique. But this may be a rare edge case.
