### ISSUE TITLE
Difference in behavior when mocking async method using .Result vs without

### ISSUE THREAD

**Issue by cyungmann** [devlooped/moq#1253]
Using Moq 4.17.2, the first two mock setups in the code below work as expected and return a `Task<string>` that resolves to `null`, while the third mock setup simply returns `null`. Is this expected?

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System.Threading.Tasks;

namespace MoqTest2
{
    public interface IFoo
    {
        Task<string?> Bar();
    }

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public async Task TestMethod1()
        {
            var mock = new Mock<IFoo>();

            mock.Setup(x => x.Bar()).Returns(() => Task.FromResult((string?)null));
            var result = await mock.Object.Bar().ConfigureAwait(false);

            mock.Setup(x => x.Bar()).ReturnsAsync((string?)null);
            result = await mock.Object.Bar().ConfigureAwait(false);

            mock.Setup(x => x.Bar().Result).Returns((string?)null);
            result = await mock.Object.Bar().ConfigureAwait(false);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1622997/165548893-d7c3e20f-e210-48ab-977a-b16fb3fa59f5.png)

**Comment by Ana-byte-bit** [comment]
It seems that problem is that Result allowed to have attribute of type `TResult` instead of `Task<TResult>`.

**Comment by stakx** [comment]
This is a bug. As it turns out, [the logic that's responsible for wrapping the return value in a completed task](https://github.com/moq/moq4/blob/eef6e1b8f9686f227e247956f4b235f9774f0afc/src/Moq/Invocation.cs#L100) only triggers for non-`null` return values, which is incorrect since `null` is a perfectly valid value (for reference types and nullable value types).
