### ISSUE TITLE
Absence of a clause in the documentation about the lack of support for sealed methods

### ISSUE THREAD

**Issue by AlexRuMath** [devlooped/moq#1256]
Moq doesn't support sealed classes/methods. You can only mock non-sealed types and virtual, non-sealed methods.

_Originally posted by @stakx in https://github.com/moq/moq4/issues/1255#issuecomment-1118962313_
Absence of a clause in the documentation about the lack of support for sealed methods

**Comment by stakx** [comment]
I suspect this was always thought of as a known, given fact, perhaps because Moq's early user base came from Rhino Mocks, which, I believe, had the same limitations. Most other open-source mocking libraries do, too (at least those based on DynamicProxy).

Feel free to add a mention of this limitation to e.g. the quickstart.

**Comment by stakx** [comment]
I've added a brief paragraph to [_Methods_ section in the Quickstart](https://github.com/Moq/moq4/wiki/Quickstart#methods) (emphasis added):

> You can setup the behavior of any of a mock's **overridable** methods [...]
