### ISSUE TITLE
System.InvalidProgramException : Cannot create boxed ByRef-like values.

### ISSUE THREAD

**Issue by RohitBinjola** [devlooped/moq#1286]
Getting below issue in MOQ unit test after upgrading the framework from 3.1 to 6.

**Message:** 
System.InvalidProgramException : Cannot create boxed ByRef-like values.

**Stack Trace:** 

```
StreamProxy.Write(ReadOnlySpan`1 buffer)
StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
StreamWriter.Flush()
```

**Test Code:** (Same code is working fine in .net core 3.1 but failing with below exception in .net 6)

```csharp
public void StreamWriter_Test()    
{
            var stream = new Mock<Stream>();
            stream.Setup(s => s.CanWrite).Returns(true);
            using var sw = new StreamWriter(stream.Object);
            sw.WriteLine("Test");
            sw.Flush();
}
```

![image](https://user-images.githubusercontent.com/18713223/187839662-078a4af8-86ae-46fe-b3d3-19c714ed2f78.png)

**Comment by stakx** [comment]
It would appear that `StreamWriter.WriteLine` calls its underlying stream's `Write(ReadOnlySpan<> buffer)` method, which Moq cannot mock (because its underlying library, DynamicProxy, cannot intercept it). That's an architectural limitation in both DynamicProxy and Moq; there's nothing that can be done about it. You'll likely need to create a mock `Stream` manually.
