### ISSUE TITLE
cannot verify on HttpMessageHandler SendAsync when calling HttpClient.PostAsync

### ISSUE THREAD

**Issue by elvia-jorn** [devlooped/moq#1315]
I'm not sure if this is a problem with Moq or with System.Net.Http.HttpClient, but here goes...

I want to test  my httpClient calls. To do this, I use the Protected part of a Mock<HttpMessageHandler> to Setup and Verify against. 

When I call httpClient.GetAsync, everything works as expected - the appropriate SendAsync function is called, and I get my expected response.

When I call httpClient.PostAsync, the appropriate SendAsync function is not called, and I get a null response.

At runtime, both GetAsync and PostAsync behave correctly.

Moq version is 4.18.3

Repro code:

```csharp
using System.Net;
using Moq;
using Moq.Protected;
using NUnit.Framework;

namespace bug;

public class Tests
{
    [Test]
    public async Task PostFails()
    {
        // Arrange
        var messageHandler = new Mock<HttpMessageHandler>();
        var httpClient = new Mock<HttpClient>(messageHandler.Object);
        var httpResponseMessage = new HttpResponseMessage()
        {
            StatusCode = HttpStatusCode.OK,
            Content = new StringContent("{\"access_token\":\"kveg\",\"expires_in\":1234}")
        };
        var mockedProtected = messageHandler.Protected();
        mockedProtected.Setup<Task<HttpResponseMessage>>("SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(httpResponseMessage);

        var underTest = new UnderTest(httpClient.Object);

        // Act
        var actual = await underTest.Post(CancellationToken.None);

        // Assert
        mockedProtected.Verify("SendAsync",
            Times.AtLeastOnce(),
            ItExpr.IsAny<HttpRequestMessage>(),
            ItExpr.IsAny<CancellationToken>());
        Assert.That(actual, Is.EqualTo(httpResponseMessage));
    }

    [Test]
    public async Task GetSucceeds()
    {
        // Arrange
        var messageHandler = new Mock<HttpMessageHandler>();
        var httpClient = new Mock<HttpClient>(messageHandler.Object);
        var httpResponseMessage = new HttpResponseMessage()
        {
            StatusCode = HttpStatusCode.OK,
            Content = new StringContent("{\"access_token\":\"kveg\",\"expires_in\":1234}")
        };
        var mockedProtected = messageHandler.Protected();
        mockedProtected.Setup<Task<HttpResponseMessage>>("SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(httpResponseMessage);

        var underTest = new UnderTest(httpClient.Object);

        // Act
        var actual = await underTest.Get(CancellationToken.None);

        // Assert
        mockedProtected.Verify("SendAsync",
            Times.AtLeastOnce(),
            ItExpr.IsAny<HttpRequestMessage>(),
            ItExpr.IsAny<CancellationToken>());
        Assert.That(actual, Is.EqualTo(httpResponseMessage));
    }

    private class UnderTest
    {
        private readonly HttpClient _httpClient;

        public UnderTest(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<HttpResponseMessage> Post(CancellationToken stoppingToken)
        {
            var fullUri = "https://www.thisuridoesnotexist.se/";
            var contentString = "some content of sorts";
            var content = new StringContent(contentString);
            var response = await _httpClient.PostAsync(fullUri, content, stoppingToken);
            return response;
        }

        public async Task<HttpResponseMessage> Get(CancellationToken stoppingToken)
        {
            var fullUri = "https://www.thisuridoesnotexist.se/";
            var response = await _httpClient.GetAsync(fullUri, stoppingToken);
            return response;
        }
    }
}
```

**Comment by stakx** [comment]
Please remember that ths is the issue tracker for Moq 4. We are here to improve Moq, not to debug user code. In order to demonstrate that we're not just doing the latter, you should state how you can be sure that you have set up the correct method, and how you know that `PostAsync` is indeed going to call it (despite Moq claiming otherwise).

**Comment by elvia-jorn** [comment]
Here's how I'm sure: run the PostFails test, and see that no "SendAsync" is triggered. Run GetSucceds, and see that "SendAsync" is triggered.
When running agains a non-mocked HttpClient, both GetAsync and PostAsync trigger "SendAsync".

**Comment by stakx** [comment]
OK, I'll take a look then, but... why are you mocking `HttpClient` at all? Isn't it enough to mock only `HttpMessageHandler`? Many of `HttpClient`'s methods aren't overridable, so Moq can't actually do much with it anyway, and you don't seem to do anything with the mock, either (apart from getting the `.Object`)...

**Comment by elvia-jorn** [comment]
Thanks a bunch. I really appreciate it :-)

That's a really good question. I suppose I could've used a live HttpClient with a mocked HttpMessageHandler. I tend to automatically grab mocks instead of live things; particularly when there are "going live across the wire" things in play.

**Comment by stakx** [comment]
As expected, Moq is working just fine. The mistake lies in your own code.

#### Long answer:

You could have replaced your `Mock<HttpMessageHandler>` with a manually written mock implementation of `HttpMessageHandler`, and you'd still have seen one of your two tests fail. So the problem doesn't lie with Moq's `.Protected()` facilities, nor with `.Verify()`.

You noticed that this problem only occurs when you use a `Mock<HttpClient>` instead of a plain `HttpClient`. This is important and will explain what goes wrong.

If you look at [the source code for `HttpClient`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs), and you see what methods get called internally when you do your `httpClient.GetAsync(uri, cancellationToken)` or `httpClient.PostAsync(uri, content, cancellationToken)`, respectively, you'll find that you end up in different `SendAsync` overloads:

* `GetAsync` gets to the ` public Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)`method overload. Note that this method is not overridable.

* `PostAsync` gets to the `public override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)` method overload. Note that this method is overridable.

When you ask Moq to mock a type, it will by default create no-op / `return default;` implementations for all overridable methods. You can change that behavior in two ways:

1. You set `mock.CallBase = true`, meaning that instead of those no-op implementations, Moq will by default call the base class' method implementations, thus allowing the base class' functionality to surface in your mock where you don't explicitly override it.

2. You `.Setup` methods to do something other than whatever the default behavior would be. You can also do a more fine-grained (method-level, instead of mock-level) `.CallBase()` this way.

Now you may start to see what's going wrong: Because you've mocked `HttpClient`, and you haven't set `CallBase = true`, Moq essentially nulls out `HttpClient`'s method implementations where it can. This includes the `SendAsync` method overload used by `PostAsync` (because it is overridable), but it does **not** include the `SendAsync` method overload used by `GetAsync` (because that one is **not** overridable). That's why `PostAsync` never arrives in your message handler, while `GetAsync` does.

#### Short answer (but please read and understand the above):

```diff
-var httpClient = new Mock<HttpClient>(messageHandler.Object);
+var httpClient = new Mock<HttpClient>(messageHandler.Object) { CallBase = true };
```

**Comment by elvia-jorn** [comment]
Thanks for the thorough explanation, and for taking a good look. I did notice the same behavior, but failed to spot that the Post and Get paths don't resolve to the same SendAsync overload. I learned something today :-)

You're a super star and deserve a beer! Happy new years

**Comment by stakx** [comment]
Thanks @elvia-jorn, have a happy new year, too! 🥳
