### ISSUE TITLE
Replacement for Moq.MethodCallReturns'2

### ISSUE THREAD

**Issue by Jepsens1** [devlooped/moq#1417]
So im currently working on some old code, and we have multiple unit test failing. And its due to the fact that "Moq.MethodCallReturns" or "Moq.MethodCallReturns´2" does not exist on the newer package we are using 4.18.3

Previous package: 4.1.1309.1617
Package we are using now: 4.18.3

I dont see anything in the changelog mentioning a replacement or removal of this method

```c#
 var type = mock.GetType().GetTypeInfo().Assembly.GetType("Moq.MethodCallReturns'2").MakeGenericType(typeof(TMock), typeof(TResult));
            type.GetMethod("SetReturnDelegate",
                    BindingFlags.InvokeMethod | BindingFlags.NonPublic | BindingFlags.Instance)
                .Invoke(mock, new object[] { func });
            return mock as IReturnsResult<TMock>;
```

**Comment by stakx** [comment]
> I dont see anything in the changelog mentioning a replacement or removal of this method

First of all, you probably meant a type called ``Moq.MethodCallReturn`2``, not `Moq.MethodCallReturns'2` &ndash; the latter didn't exist in version 4.1.1309.1617, as far as I can tell.

Second, this was an `internal` type and not part of the public API, which is why the changelog does not need to mention any changes to (or even the removal of) it. If you use Reflection to get at private Moq bits, you basically have no guarantee that this is going to continue working forever. If you want to be safer, use only the public API.

**Comment by Jepsens1** [comment]
Yes looking at the package in resharper dotpeek, its called Moq.MethodCallReturn`2

This code was back in 2017 and has not being touched since, so this will require a complete rework of the unit test to be part of the public API and due to the fact there is no replacement, right?

**Comment by stakx** [comment]
Moq internals have been extensively refactored since 2017, so if you are relying on internal implementation details (which is obviously not a recommended approach) then yes, you'll have to adjust your code.

The functionality that was once located in `Moq.MethodCallReturn<,>` likely still exists somewhere else (possibly in `Moq.Language.Flow.NonVoidSetupPhrase<,>` and `MethodCall`), but I don't remember the exact details about that particular refactoring. If you want to bypass the public API, you're basically on your own.
